# ABC/XYZ-анализ в денежном выражении

**Цель:** Провести ABC/XYZ-анализ по денежным показателям на всём датасете; построить сводные таблицы и тепловые карты по категориям.

**Вход:** `df_final_себестоимость_выручка_ABC_XYZ_кол.xlsx` (не приложен).

**Основные шаги:** агрегация выручки, кумулятивная доля, ABC-классификация, коэффициент вариации, XYZ-классификация, тепловые карты.

**Навыки:** pandas, numpy, seaborn, ABC/XYZ.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
valtec_df_common = pd.read_excel('df_final_себестоимость_выручка_ABC_XYZ_кол.xlsx')

In [3]:
valtec_df_common

,Код,Номенклатура,Ед_изм,Дата,Начальный_остаток,Приход,Расход,Конечный_остаток,Выручка,Категория,Год,ABC_категория,ABC_2024,XYZ_2024,XYZ_all
0,00-00000019,Труба 75 Базальт ЭКО 8.4 упак 8 м кратно ...,м,2021-08-01,20379.08,48774.81,56835.83,25834.47,75469.85,2,2021,A,A,X,X
1,00-00000019,Труба 75 Базальт ЭКО 8.4 упак 8 м кратно ...,м,2022-08-01,0.00,86530.76,86530.76,0.00,106442.65,2,2022,A,A,X,X
2,00-00000019,Труба 75 Базальт ЭКО 8.4 упак 8 м кратно ...,м,2023-08-01,0.00,30935.01,30935.01,0.00,38734.71,2,2023,A,A,X,X
3,00-00000019,Труба 75 Базальт ЭКО 8.4 упак 8 м кратно ...,м,2024-08-01,0.00,59738.32,59738.32,0.00,90496.00,2,2024,A,A,X,X
4,00-00000019,Труба 75 Базальт ЭКО 8.4 упак 8 м кратно ...,м,2021-04-01,61571.85,7941.28,46342.08,23171.05,57718.98,2,2021,A,A,X,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723430,ЦБ-00000057,Зонт 50 вентиляционный Контур СКЛАД (10),шт,2021-01-01,211.72,175.00,64.45,322.27,89.88,1,2021,C,C,Y,X
723431,ЦБ-00000057,Зонт 50 вентиляционный Контур СКЛАД (10),шт,2022-01-01,293.31,0.00,0.00,293.31,0.00,1,2022,C,C,Y,X
723432,ЦБ-00000057,Зонт 50 вентиляционный Контур СКЛАД (10),шт,2023-01-01,244.84,0.00,104.93,139.91,172.06,1,2023,C,C,Y,X
723433,ЦБ-00000057,Зонт 50 вентиляционный Контур СКЛАД (10),шт,2024-01-01,270.70,0.00,0.00,270.70,0.00,1,2024,C,C,Y,X
723434,ЦБ-00000057,Зонт 50 вентиляционный Контур СКЛАД (10),шт,2025-01-01,413.10,0.00,0.00,413.10,0.00,1,2025,C,C,Y,X

In [3]:
valtec_df_common

,Код,Номенклатура,Ед_изм,Дата,Начальный_остаток,Приход,Расход,Конечный_остаток,Выручка,Категория,...,Начальный_остаток_шт,Расход_шт,Приход_шт,Квартал,ABC_valtec,XYZ_valtec,ABC_2023,XYZ_2023,ABC_2024,XYZ_2024
0,00-00000184,Удлинитель 1/2 10 мм кругл. Valtec.(30) СКЛАД...,шт,2021-08-01,0.00,1743.33,784.50,871.66,833.09,1,...,0.0,18.0,40,3,B,X,B,X,B,X
1,00-00000184,Удлинитель 1/2 10 мм кругл. Valtec.(30) СКЛАД...,шт,2022-08-01,47.29,896.67,674.25,269.71,746.25,1,...,1.0,15.0,20,3,B,X,B,X,B,X
2,00-00000184,Удлинитель 1/2 10 мм кругл. Valtec.(30) СКЛАД...,шт,2023-08-01,534.02,485.83,631.33,388.52,724.52,1,...,11.0,13.0,10,3,B,X,B,X,B,X
3,00-00000184,Удлинитель 1/2 10 мм кругл. Valtec.(30) СКЛАД...,шт,2024-08-01,1155.00,525.00,1575.00,105.00,1840.05,1,...,22.0,30.0,10,3,B,X,B,X,B,X
4,00-00000184,Удлинитель 1/2 10 мм кругл. Valtec.(30) СКЛАД...,шт,2021-04-01,0.00,0.00,0.00,0.00,0.00,1,...,0.0,0.0,0,2,B,X,B,X,B,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40285,0Т-00054517,"яКлапан обратный 1/2"" для водосчетчика (под сг...",шт,2021-01-01,0.00,0.00,0.00,0.00,0.00,2,...,0.0,0.0,0,1,C,Z,C,Z,B,Z
40286,0Т-00054517,"яКлапан обратный 1/2"" для водосчетчика (под сг...",шт,2022-01-01,0.00,0.00,0.00,0.00,0.00,2,...,0.0,0.0,0,1,C,Z,C,Z,B,Z
40287,0Т-00054517,"яКлапан обратный 1/2"" для водосчетчика (под сг...",шт,2023-01-01,0.00,0.00,0.00,0.00,0.00,2,...,0.0,0.0,0,1,C,Z,C,Z,B,Z
40288,0Т-00054517,"яКлапан обратный 1/2"" для водосчетчика (под сг...",шт,2024-01-01,0.00,0.00,0.00,0.00,0.00,2,...,0.0,0.0,0,1,C,Z,C,Z,B,Z
40289,0Т-00054517,"яКлапан обратный 1/2"" для водосчетчика (под сг...",шт,2025-01-01,86.33,0.00,0.00,86.33,0.00,2,...,4.0,0.0,0,1,C,Z,C,Z,B,Z

In [4]:
# Фильтруем данные по 2024 году
df_2024 = valtec_df_common[valtec_df_common['Год'] == 2024].copy()

# Создаем объединённую категорию
df_2024['ABC_XYZ_2024'] = df_2024['ABC_2024'] + df_2024['XYZ_2024']

# Группируем по объединённой категории
summary_2024 = df_2024.groupby('ABC_XYZ_2024').agg(
    Количество_позиций=('Код', 'nunique'),
    Сумма_остатков=('Начальный_остаток', 'sum'),
    Сумма_расхода=('Расход', 'sum'),
    Сумма_выручки=('Выручка', 'sum')
).reset_index()

# Сортируем по названию категории (по желанию)
summary_2024 = summary_2024.sort_values(by='ABC_XYZ_2024')

summary_2024

,ABC_XYZ_2024,Количество_позиций,Сумма_остатков,Сумма_расхода,Сумма_выручки
0,AX,467,1.574524e+08,2.064087e+08,2.240476e+08
1,AY,221,5.394300e+07,7.579379e+07,9.224833e+07
2,AZ,321,5.018426e+07,1.141673e+08,1.371050e+08
3,BX,563,3.992494e+07,3.137701e+07,3.153750e+07
4,BY,414,2.140018e+07,1.802445e+07,2.079951e+07
5,BZ,656,1.335141e+07,2.852650e+07,3.277157e+07
6,CX,684,2.459640e+07,1.252868e+07,5.907629e+06
7,CY,1079,2.228884e+07,7.946804e+06,7.817537e+06
8,CZ,9780,4.813313e+07,1.453011e+07,1.463796e+07

summary_2024.to_excel('final_df_abc_xyz_summary_2024.xlsx', index=False)

In [6]:
valtec_df_common[valtec_df_common['Дата'] == '2025-01-01']['Начальный_остаток'].sum()

48986985.88

In [7]:
valtec_df_common[valtec_df_common['Дата'] == '2024-01-01']['Начальный_остаток'].sum()

25394180.380000003

In [8]:
valtec_df_common[valtec_df_common['Дата'] == '2023-01-01']['Начальный_остаток'].sum()

19095015.51

In [5]:
# Группируем по объединённой категории
summ_abc_2024 = df_2024.groupby('ABC_2024').agg(
    Количество_позиций=('Код', 'nunique'),
    Сумма_остатков=('Начальный_остаток', 'sum'),
    Сумма_расхода=('Расход', 'sum'),
    Сумма_выручки=('Выручка', 'sum')
).reset_index()

# Сортируем по названию категории (по желанию)
summ_abc_2024 = summ_abc_2024.sort_values(by='ABC_2024')

summ_abc_2024

  ABC_2024  Количество_позиций  Сумма_остатков  Сумма_расхода  Сумма_выручки
0        A                  90     12702555.40    15934321.56    19168937.13
1        B                 119      3655697.14     2971265.35     3617780.78
2        C                 581      3623280.36     1012746.00     1212930.42

In [6]:
# Фильтруем данные по 2023 году
df_2023 = valtec_df_common[valtec_df_common['Год'] == 2023].copy()

# Создаем объединённую категорию
df_2023['ABC_XYZ_2023'] = df_2023['ABC_2023'] + df_2023['XYZ_2023']

# Группируем по объединённой категории
summary_2023 = df_2023.groupby('ABC_XYZ_2023').agg(
    Количество_позиций=('Код', 'nunique'),
    Сумма_остатков=('Начальный_остаток', 'sum'),
    Сумма_расхода=('Расход', 'sum'),
    Сумма_выручки=('Выручка', 'sum')
).reset_index()

# Сортируем по названию категории (по желанию)
summary_2023 = summary_2023.sort_values(by='ABC_XYZ_2023')

# Отображаем результат
summary_2023

,ABC_XYZ_2023,Количество_позиций,Сумма_остатков,Сумма_расхода,Сумма_выручки
0,AX,64,8492669.17,10213537.41,12333032.87
1,AY,19,1487719.83,2574408.07,3118483.97
2,AZ,17,370969.71,2057146.91,2474759.02
3,BX,64,1980371.44,1326679.00,1605386.25
4,BY,36,596658.47,672555.09,829139.76
5,BZ,42,553111.21,744128.27,924544.32
6,CX,16,294837.43,89250.17,109545.40
7,CY,83,951842.87,319821.20,399306.88
8,CZ,449,2105946.17,499458.16,618160.68

summary_2023.to_excel('summary_2023.xlsx', index=False)

In [7]:
# Дополнительно: группировка только по ABC_2023
summ_abc_2023 = df_2023.groupby('ABC_2023').agg(
    Количество_позиций=('Код', 'nunique'),
    Сумма_остатков=('Начальный_остаток', 'sum'),
    Сумма_расхода=('Расход', 'sum'),
    Сумма_выручки=('Выручка', 'sum')
).reset_index()

# Сортируем по названию категории (по желанию)
summ_abc_2023 = summ_abc_2023.sort_values(by='ABC_2023')

# Отображаем результат
summ_abc_2023

  ABC_2023  Количество_позиций  Сумма_остатков  Сумма_расхода  Сумма_выручки
0        A                 100     10351358.71    14845092.39    17926275.86
1        B                 142      3130141.12     2743362.36     3359070.33
2        C                 548      3352626.47      908529.53     1127012.96